
[api]
baseuri = "https://ca-core.unhexium.dev"
workername = "example"
token = "replaceme"

[job]
tempdir = "/tmp/ca-workdir/ca-worker-%s"
jobdirpattern = "job-%s"
analysis_program = "ca-analyzer"
result_file = "outfile.json"
